redgold-io/redgold

- .github/workflows/ci.yml
- Cargo.toml
- bin/bump_versions.sh
- bin/cargo_publish.sh
- bin/get_version.sh
- data/Cargo.toml
- schema/Cargo.toml
#63 typo in bash script reference in CI
> Fix for CI

- Cargo.toml
- bin/build_python.sh
- python/model/.gitignore
- python/model/README.md
- python/model/main.py
- python/model/setup.py
- src/trust/embed/mod.rs
- src/trust/mod.rs
Not complete, but sufficient demonstration. Fixes #9
> Working build script and simple example for GE

- Cargo.toml
- src/api/rosetta/mod.rs
- src/core/peer_rx_event_handler.rs
- src/core/process_transaction.rs
- src/e2e/alert.rs
- src/infra/deploy.rs
- src/multiparty/gg20_keygen.rs
- src/multiparty/gg20_signing.rs
- src/multiparty/gg20_sm_client.rs
- src/util/hashviz.rs
- tests_backup/default_args_example.rs
- tests_backup/hdpath_wallet.rs
Remove a bunch of unused dependencies
> Dependency prune

- src/api/public_api.rs
- src/infra/deploy.rs
- src/infra/mod.rs
- src/node.rs
- src/resources/infra/ops_services/services-all.yml
- src/util/cli/arg_parse_config.rs
- src/util/cli/args.rs
- src/util/cli/commands.rs
Also fix watcher interval and bug in response / request decoding.
> Fix deploy scripts for CLI

- src/api/public_api.rs
- src/core/internal_message.rs
- src/core/peer_event_handler.rs
- src/core/relay.rs
- src/infra/deploy.rs
- src/infra/mod.rs
- src/node.rs
- src/resources/infra/ops_services/services-all.yml
- src/util/cli/arg_parse_config.rs
- src/util/cli/args.rs
- src/util/cli/commands.rs
> 
2023-07-27T09:56:02.577840Z ERROR redgold::util::logging: {"code":27,"description":"","description_extended":"","message":"sending on a closed channel Error sending message back on response channel ","details":[],"retriable":false,"stacktrace":"   0: redgold_schema::error_msg\n   1: <flume::Sender<T> as redgold::core::internal_message::SendErrorInfo<T>>::send_err\n   2: redgold::core::peer_event_handler::PeerOutgoingEventHandler::send_message_rest::{{closure}}\n   3: <futures_util::stream::futures_unordered::FuturesUnordered<Fut> as futures_core::stream::Stream>::poll_next\n   4: <futures_util::stream::try_stream::try_for_each_concurrent::TryForEachConcurrent<St,Fut,F> as core::future::future::Future>::poll\n   5: redgold::core::peer_event_handler::PeerOutgoingEventHandler::new::{{closu …
> Sending on a Closed channel

- schema/json_build_config.json
- schema/src/multiparty.rs
- schema/src/structs.proto
- src/core/relay.rs
- src/infra/deploy.rs
- src/multiparty/gg20_keygen.rs
- src/multiparty/gg20_signing.rs
- src/multiparty/gg20_sm_client.rs
- src/multiparty/gg20_sm_manager.rs
- src/multiparty/initiate_mp.rs
- src/node.rs
- src/node_config.rs
- src/util/cli/args.rs
- src/util/cli/commands.rs
Root cause was issue unique index did not match party index. Also added authorization for everything but subscribe.
> Working multiparty fix

- docs/content/3.whitepaper/4.products.md
- docs/content/3.whitepaper/5.addendum.md
> Rewrite whitepaper ending pages

- data/migrations/20220602030203_utxo.sql
- data/migrations/20220602030250_utxo.sql
- data/src/config.rs
- data/src/transaction_store.rs
- schema/json_build_config.json
- schema/src/structs.proto
- schema/src/transaction.rs
- schema/src/transaction_builder.rs
- schema/src/utxo_entry.rs
- src/api/explorer/mod.rs
- src/api/faucet.rs
- src/api/hash_query.rs
- src/api/public_api.rs
- src/api/rosetta/handlers.rs
- src/core/process_transaction.rs
- src/core/transaction.rs
- src/data/data_store.rs
- src/data/download.rs
- src/data/utxo.rs
- src/e2e/tx_gen.rs
- src/e2e/tx_submit.rs
- src/hardware/trezor.rs
- src/multiparty/watcher.rs
- src/node.rs
- src/util/cli/commands.rs
- vue-explorer/src/components/BriefTransaction.vue
- vue-explorer/src/components/DashboardScreen.vue
Refactoring other types and cleaning up datastore, dealing with duplicate genesis issue on utxo commit, other things.
> Fix core issue with zero amount genesis funding on watcher.

- schema/src/lib.rs
- schema/src/util/btc_wallet.rs
- schema/src/util/mnemonic_support.rs
- schema/src/util/mod.rs
- src/api/explorer/server.rs
- src/multiparty/watcher.rs
> Explorer route fix and bitcoin local private key send function and test

- schema/src/util/bdk_example.rs
- src/infra/deploy.rs
- src/multiparty/watcher.rs
- src/node.rs
- src/util/trace_setup.rs
> Include additional debug info in watcher.

- schema/src/util/bdk_example.rs
- src/infra/deploy.rs
- src/multiparty/watcher.rs
- src/node.rs
- src/util/trace_setup.rs
> 255 zero price

- schema/src/util/btc_wallet.rs
- src/multiparty/watcher.rs
> Dump pubkey hex for deposit to logs

- data/src/config.rs
- data/src/peer.rs
- schema/src/constants.rs
- schema/src/lib.rs
- schema/src/structs.proto
- schema/src/transaction.rs
- schema/src/transaction_builder.rs
- schema/src/util/mnemonic_support.rs
- schema/src/utxo_entry.rs
- src/api/about.rs
- src/api/control_api.rs
- src/api/explorer/mod.rs
- src/api/hash_query.rs
- src/api/mod.rs
- src/api/public_api.rs
- src/core/peer_event_handler.rs
- src/core/peer_rx_event_handler.rs
- src/core/process_transaction.rs
- src/core/relay.rs
- src/infra/deploy.rs
- src/multiparty/gg20_keygen.rs
- src/multiparty/gg20_signing.rs
- src/multiparty/gg20_sm_client.rs
- src/multiparty/initiate_mp.rs
- src/node.rs
- src/node_config.rs
- src/observability/dynamic_prometheus.rs
- src/util/cli/arg_parse_config.rs
- tests/local_e2e_it.rs
Part of #45 
Doesn't update deploy script yet, just internal calls for config store.
> Preparation of config changes for peerId / nmd from store

- schema/src/util/btc_wallet.rs
- src/multiparty/watcher.rs
> More debug information for mp watcher

- schema/Cargo.toml
- schema/src/util/mnemonic_support.rs
- src/e2e/mod.rs
- src/gui/app_loop.rs
- src/infra/deploy.rs
- src/infra/mod.rs
- src/util/cli/arg_parse_config.rs
- src/util/cli/args.rs
- src/util/cli/commands.rs
- src/util/cli/data_folder.rs
> Implement local mnemonic generation for remote deployments and peer_id cold

- schema/src/util/btc_wallet.rs
- src/api/hash_query.rs
Part of #255. Required for explorer
> Query based on bitcoin address.

- data/src/transaction_store.rs
- schema/Cargo.toml
- schema/src/hash.rs
- schema/src/util/mod.rs
- schema/src/util/xor_distance.rs
- src/node.rs
Couldn't get the sqlite function working properly, needs to be done as a udf later if necessary.
> Xor distance function, partial stub for sqlite

- schema/src/hash.rs
- schema/src/util/mnemonic_support.rs
- src/gui/app_loop.rs
- src/gui/cold_wallet.rs
- src/gui/common.rs
- src/gui/hot_wallet.rs
- src/gui/keys_tab.rs
- src/gui/local_stored_state.rs
- src/gui/mod.rs
- src/gui/util.rs
- src/gui/wallet_tab.rs
- src/node_config.rs
> Working hot wallet

- schema/json_build_config.json
- schema/src/structs.proto
- src/core/discovery.rs
- src/core/peer_rx_event_handler.rs
> Fix peer update transaction for discovery for belayed node metadata

- .github/workflows/ci.yml
- bin/install_mac_build_deps.sh
Part of #187 Have to verify build profile for environment branch works for dependency on release. May require additional fix.
> Fix CI related issue for Mac builds

- .github/workflows/ci.yml
> Versioned release and short build checksum

- .github/workflows/ci.yml
> Missing dev dependency

- .github/workflows/ci.yml
- Cargo.toml
- bin/release_branches.sh
- data/Cargo.toml
- executor/Cargo.toml
- schema/Cargo.toml
> Should fix staging issue

- Cargo.toml
- sdk-client/Cargo.toml
- src/infra/deploy.rs
- src/util/cli/commands.rs
Re-enable executor module now that build bdk is fixed.
> Executor again re-enabled

- Cargo.toml
- schema/src/public_key.rs
- schema/src/resources/seeds/seeds-old.csv
- schema/src/seeds.rs
- src/api/mod.rs
- src/api/public_api.rs
- src/core/internal_message.rs
- src/core/mempool.rs
- src/core/mod.rs
- src/core/process_transaction.rs
- src/core/relay.rs
- src/core/seeds.rs
- src/node.rs
- src/node_config.rs
- src/util/cli/arg_parse_config.rs
> Mempool queue

- data/Cargo.toml
- data/migrations/20220602030556_state.sql
- data/src/lib.rs
- data/src/state_store.rs
- keys/src/util/mnemonic_words.rs
- schema/json_build_config.json
- schema/src/contract.rs
- schema/src/lib.rs
- schema/src/output.rs
- schema/src/proto/structs.proto
- schema/src/transaction.rs
- schema/src/transaction_builder.rs
- sdk/compile.sh
- src/api/mod.rs
- src/core/peer_rx_event_handler.rs
- src/e2e/tx_gen.rs
- src/e2e/tx_submit.rs
- src/genesis.rs
- src/node.rs
> Executor state store schema and contract call setup

- .github/workflows/ci.yml
- Cargo.toml
- data/Cargo.toml
- executor/Cargo.toml
- keys/Cargo.toml
- schema/Cargo.toml
- sdk-client/Cargo.toml
- sdk/Cargo.toml
> Staging docs / explorer test release 0.1.11

- data/migrations/20220602030556_state.sql
- data/src/state_store.rs
- executor/src/extism_wrapper.rs
- schema/json_build_config.json
- schema/src/hash.rs
- schema/src/lib.rs
- schema/src/output.rs
- schema/src/proto/structs.proto
- schema/src/transaction_builder.rs
- schema/src/util/xor_distance.rs
- sdk/src/example.rs
- src/core/contract/contract_state_manager.rs
- src/core/process_transaction.rs
- src/core/relay.rs
- src/core/stream_handlers.rs
- src/e2e/tx_gen.rs
- src/e2e/tx_submit.rs
- src/node.rs
- src/node_config.rs
- src/resources/infra/redgold-only.yml
> Working executor request call -- lots of missing pieces but e2e test done

- Cargo.toml
- data/Cargo.toml
- executor/Cargo.toml
- keys/Cargo.toml
- schema/Cargo.toml
- sdk-client/Cargo.toml
- sdk/Cargo.toml
- vue-explorer/src/components/DashboardScreen.vue
- vue-explorer/src/components/mixins/fetchHashInfo.js
Explorer url is hardcoded to dev
> Fix for staging url

- .github/workflows/ci.yml
Should compile and build release correctly. Fixes #44
> Implement release process for windows using msys2

- Cargo.toml
- keys/Cargo.toml
- keys/src/address_external.rs
- keys/src/lib.rs
- keys/src/util/mnemonic_support.rs
- src/api/explorer/mod.rs
- src/gui/app_loop.rs
- src/gui/keys_tab.rs
- src/hardware/trezor.rs
- src/multiparty/watcher.rs
- src/util.rs
> Xpub metadata and write to file in keys tab

- .github/workflows/ci.yml
- keys/src/util/mnemonic_support.rs
- schema/src/local_stored_state.rs
- src/gui/app_loop.rs
- src/gui/keys_tab.rs
- src/gui/wallet_tab.rs
- src/node_config.rs
- src/util/cli/arg_parse_config.rs
> Fixes for keys tab, csv parse xpub

- bin/import_grafana_alerts.sh
- src/api/public_api.rs
- src/infra/deploy.rs
- src/resources/infra/ops_services/kibana_setup.sh
- src/resources/infra/ops_services/services-all.yml
> kibana fix for deploy

- src/core/peer_rx_event_handler.rs
- src/core/relay.rs
- src/node.rs
- src/node_config.rs
part of #397  not sure if this will work yet
> Fix for alias not loading

- schema/src/transaction.rs
- src/api/explorer/mod.rs
- src/infra/deploy.rs
- vue-explorer/src/components/mixins/fetchHashInfo.js
> Wrong network env on deploy

- schema/src/transaction.rs
- src/api/faucet.rs
- src/e2e/mod.rs
- src/genesis.rs
> Genesis test faucet

- src/gui/app_loop.rs
> Implement parse servers from CSV

- schema/src/local_stored_state.rs
- schema/src/output.rs
- schema/src/servers.rs
- schema/src/transaction.rs
- schema/src/transaction_builder.rs
- src/api/public_api.rs
- src/gui/app_loop.rs
- src/gui/common.rs
- src/gui/home.rs
- src/gui/tabs/identity_tab.rs
- src/gui/wallet_tab.rs
- src/hardware/trezor.rs
- src/infra/deploy.rs
- src/node.rs
- src/node_config.rs
- src/util/cli/commands.rs
Rejected by cluster for unrelated error but otherwise tested. Fixes #316
> Generate peer transaction - Implement everything apart from fee

- src/api/mod.rs
> Add default trace_id

- .github/workflows/ci.yml
- data/migrations/20220602030204_transactions.sql
- data/src/peer.rs
- data/src/transaction_store.rs
- executor/src/evm_invoke/fork_ref_transact.rs
- executor/src/evm_invoke/fork_ref_transact2.rs
- executor/src/evm_invoke/revm_wrapper.rs
- keys/src/request_support.rs
- schema/json_build_config.json
- schema/src/block.rs
- schema/src/errors.rs
- schema/src/peers.rs
- schema/src/proto/structs.proto
- schema/src/public_key.rs
- schema/src/transaction.rs
- schema/src/util/xor_distance.rs
- src/api/rosetta/mod.rs
- src/core/data_discovery.rs
- src/core/discovery.rs
- src/core/mempool.rs
- src/core/mod.rs
- src/core/peer_rx_event_handler.rs
- src/core/process_transaction.rs
- src/core/recent_download.rs
- src/core/relay.rs
- src/core/resolver.rs
- src/node.rs
- src/util/metrics_registry.rs
> Data discovery and recent download

- schema/src/local_stored_state.rs
- src/gui/app_loop.rs
- src/gui/mod.rs
- src/gui/tabs/hot_wallet.rs
- src/gui/tabs/keys_tab.rs
- src/gui/tabs/mod.rs
- src/gui/tabs/server_tab.rs
- src/gui/tabs/settings_tab.rs
- src/gui/wallet_tab.rs
- src/infra/deploy.rs
- src/util/cli/args.rs
> GUI deploy mainnet issue

- docs-repo/certificate_renewal
- vue-explorer/src/components/hash_types/AddressDetail.vue
> Fix the GUI

- keys/src/util/btc_wallet.rs
- src/multiparty/watcher.rs
- src/test/external_amm_integration.rs
- src/test/mod.rs
Address balance not updating properly for testnet.
> Debugging watcher address balance

- keys/Cargo.toml
- keys/src/eth/example.rs
- keys/src/eth/mod.rs
- keys/src/lib.rs
- schema/json_build_config.json
- schema/src/lib.rs
- schema/src/proto/structs.proto
- schema/src/signature.rs
- schema/src/util/lang_util.rs
- src/api/rosetta/spec.rs
- src/multiparty/gg20_signing.rs
- src/scrape/mod.rs
- src/test/node_e2e.rs
- src/util/trace_setup.rs
> Working ETH multiparty implementation

- schema/src/public_key.rs
- src/api/rosetta/models.rs
- src/gui/tabs/server_tab.rs
- src/infra/deploy.rs
- src/multiparty/mod.rs
- src/multiparty/offline_debug.rs
- src/util/cli/data_folder.rs
> 451 ssh backup

- Cargo.toml
- src/gui/tabs/server_tab.rs
- src/infra/deploy.rs
- src/infra/mod.rs
- src/multiparty/initiate_mp.rs
- src/util/cli/arg_parse_config.rs
- src/util/cli/commands.rs
- src/util/cmd.rs
> Openssl / ssh2 dependency removed, tested from gui and cli

- .cargo/config.toml
- .github/workflows/ci.yml
- executor/Cargo.toml
> Fix windows build

- Cargo.toml
- keys/src/transaction_support.rs
- schema/src/transaction.rs
- src/api/faucet.rs
- src/core/mempool.rs
- src/core/observation.rs
- src/core/peer_rx_event_handler.rs
- src/core/process_transaction.rs
- src/core/relay.rs
- src/core/transact/tx_builder_supports.rs
- src/e2e/mod.rs
- src/e2e/tx_gen.rs
- src/e2e/tx_submit.rs
- src/genesis.rs
- src/gui/app_loop.rs
- src/gui/initialize.rs
- src/gui/tabs/identity_tab.rs
- src/gui/wallet_tab.rs
- src/hardware/trezor.rs
- src/infra/deploy.rs
- src/multiparty/watcher.rs
- src/node_config.rs
- src/scrape/mod.rs
- src/test/external_amm_integration.rs
- src/test/node_e2e.rs
- src/util/cli/commands.rs
- tests/local_e2e_it.rs
> Validator & GUI fix

- src/api/faucet.rs
- src/core/peer_rx_event_handler.rs
- src/core/relay.rs
- src/gui/wallet_tab.rs
- vue-explorer/src/components/FaucetRequest.vue
> Faucet fixes

- keys/src/address_support.rs
- vue-explorer/src/components/FaucetRequest.vue
> Working faucet impl

- vue-explorer/src/components/BriefPeer.vue
> Fix explorer rendering issue on field

- data/src/utxo_store.rs
- keys/src/lib.rs
- schema/src/transaction.rs
- src/core/process_observation.rs
- src/core/process_transaction.rs
- src/core/recent_download.rs
- src/core/relay.rs
- src/e2e/tx_gen.rs
- src/e2e/tx_submit.rs
- src/lib.rs
- src/sanity/historical_parity.rs
- src/sanity/mod.rs
- src/test/node_e2e.rs
Part of #516 -- still found parity check issue
> Observation security / other stuff

- data/src/transaction_store.rs
- data/src/utxo_store.rs
- schema/Cargo.toml
- schema/json_build_config.json
- schema/src/lib.rs
- schema/src/util/mod.rs
- src/api/explorer/mod.rs
- src/multiparty/watcher.rs
- src/resources/infra/matrix-base-domain.conf
- src/sanity/historical_parity.rs
- vue-explorer/src/components/hash_types/TransactionDetail.vue
part of #516 
also ui more info
> Parity checks and debugging

- .github/workflows/ci.yml
- bin/test.sh
- src/api/public_api.rs
- src/api/rosetta/mod.rs
- src/core/block_formation.rs
- src/core/resolver.rs
- src/core/transaction.rs
- src/data/download.rs
- src/e2e/tx_gen.rs
- src/genesis.rs
- src/node.rs
- src/node_config.rs
- src/test/node_e2e.rs
> 568 test parallelism

- src/test/double_spend_it.rs
- src/test/mod.rs
> double spend test

- docs/content/3.whitepaper/1.introduction.md
> Whitepaper edit

- schema/src/conf/rg_args.rs
- src/api/hash_query.rs
- src/gui/app_loop.rs
- src/gui/components/swap.rs
- src/gui/home.rs
- src/gui/tabs/transact/wallet_tab.rs
- src/party/central_price.rs
- src/party/party_stream.rs
> 632 swap gui

- schema/src/explorer.rs
- schema/src/output.rs
- schema/src/party/party_events.rs
- schema/src/transaction.rs
- schema/src/tx/currency_amount.rs
- src/api/explorer/mod.rs
- src/core/relay.rs
- src/gui/app_loop.rs
- src/gui/components/swap.rs
- src/party/party_stream.rs
- vue-explorer/src/components/HashDetails.vue
- vue-explorer/src/components/TransactionSwapInfo.vue
- vue-explorer/src/components/hash_types/ExternalTxid.vue
- vue-explorer/src/components/hash_types/TransactionDetail.vue
- vue-explorer/src/components/mixins/fetchHashInfo.js
> Explorer swap tracking addition

- crates/gui/src/common.rs
- crates/gui/src/components/transaction_table.rs
- crates/rpc-integ/src/eth/eth_wallet.rs
- crates/rpc-integ/src/eth/validate_tx.rs
- crates/schema/src/explorer.rs
- crates/schema/src/party/party_events.rs
- crates/schema/src/tx/currency_amount.rs
- src/api/explorer/mod.rs
- src/gui/app_loop.rs
- src/node.rs
- src/party/order_fulfillment.rs
- src/party/party_stream.rs
- src/test/daily_e2e/mod.rs
- src/test/debug_scripts/mod.rs
- src/test/debug_scripts/party_gas_fee_insufficient.rs
- src/test/harness/amm_harness.rs
- src/test/node_e2e.rs
- vue-explorer/src/components/hash_types/AddressDetail.vue
Lower gas as well on testnet. Fixes #699
> Fix gas minimum on order
